#!/bin/sh

commit_msg=$(cat "$1")

pattern='^GLF-[0-9]+ '

if ! echo "$commit_msg" | grep -Eq "$pattern"; then
    echo ""
    echo "ERROR: Commit message must start with a Jira issue ID."
    echo "Example: GLF-1 Create Member entity"
    echo ""
    exit 1
fi